USE BOOKSTORE;

INSERT INTO FORMAT VALUES (NULL, 'POCKET');
INSERT INTO FORMAT VALUES (NULL, 'E-BOOK');
INSERT INTO FORMAT VALUES (NULL, 'PAPERBACK');
INSERT INTO FORMAT VALUES (NULL, 'HARDCOVER');
INSERT INTO FORMAT VALUES (NULL, 'MASS PAPERBACK');