CREATE DATABASE BOOKSTORE;

USE BOOKSTORE;

CREATE TABLE AUTHOR(
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(200) NOT NULL,
    NATIONALITY VARCHAR(100) NOT NULL
);

CREATE TABLE PUBLISHER(
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(200) NOT NULL
);

CREATE TABLE FORMAT(
    ID INT AUTO_INCREMENT PRIMARY KEY,
    FORMAT VARCHAR(200) NOT NULL
);

CREATE TABLE BOOK(
    ID INT AUTO_INCREMENT PRIMARY KEY,
    TITLE VARCHAR(300) NOT NULL,
    PUBLISHED_AT CHAR(4),
    FORMAT_ID INT NOT NULL,
    AUTHOR_ID INT,
    PUBLISHER_ID INT,
    WAS_READ CHAR(3) NOT NULL
);

-- THE IDEIA ON THE START IS GO COM 0 TO 5
CREATE TABLE CLASSIFICATION(
    ID INT AUTO_INCREMENT PRIMARY KEY,
    STARTS CHAR(1) NOT NULL,
    BOOK_ID INT
);


ALTER TABLE CLASSIFICATION
ADD CONSTRAINT FK_CLASSIFICATION_BOOK
FOREIGN KEY (BOOK_ID)
REFERENCES BOOK(ID);

ALTER TABLE BOOK
ADD CONSTRAINT FK_BOOK_AUTHOR
FOREIGN KEY (AUTHOR_ID)
REFERENCES AUTHOR(ID);

ALTER TABLE BOOK 
ADD CONSTRAINT FK_PUBLISHER
FOREIGN KEY (PUBLISHER_ID)
REFERENCES PUBLISHER(ID);

ALTER TABLE BOOK
ADD CONSTRAINT FK_BOOK_FORMAT
FOREIGN KEY (FORMAT_ID)
REFERENCES FORMAT(ID);

/* SOME BUSINESS RULES */

ALTER TABLE PUBLISHER
ADD CONSTRAINT UNIQUE_PUBISHER
UNIQUE (NAME);

ALTER TABLE AUTHOR
ADD CONSTRAINT UNIQUE_AUTHOR
UNIQUE (NAME);