SELECT  BOOK.ID,
        BOOK.TITLE,
        AUTHOR.NAME,
        AUTHOR.NATIONALITY,
        FORMAT.FORMAT,
        PUBLISHER.NAME,
        BOOK.WAS_READ, 
FROM BOOK
INNER JOIN AUTHOR
	ON BOOK.AUTHOR_ID = AUTHOR.ID
INNER JOIN FORMAT 
    ON BOOK.FORMAT_ID = FORMAT.ID
INNER JOIN PUBLISHER
    ON BOOK.PUBLISHER_ID = PUBLISHER.ID;


/* MORE READABLE THAN THE OTHER ONE */
SELECT  BOOK.TITLE,
        AUTHOR.NAME,
        AUTHOR.NATIONALITY,
        FORMAT.FORMAT,
        PUBLISHER.NAME, 
        BOOK.WAS_READ
FROM BOOK
INNER JOIN AUTHOR
	ON BOOK.AUTHOR_ID = AUTHOR.ID
INNER JOIN FORMAT 
    ON BOOK.FORMAT_ID = FORMAT.ID
INNER JOIN PUBLISHER
    ON BOOK.PUBLISHER_ID = PUBLISHER.ID
ORDER BY BOOK.TITLE;

/* AFTER INSERT ISBN THERE WILL BE MORE PROJECTIONS */